# -*- coding: utf-8 -*-
"""YoloV8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kjt8DmbueO17xoE5fpngdYdJW7x1psCn
"""

!nvidia-smi

!pip install ultralytics

!yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'

"""# 1. **Detection**"""

!yolo task=detect mode=predict model=yolov8n.pt source="/content/bus.jpg"

"""# 2. **Segmentation**"""

!yolo task=segment mode=predict model=yolov8n-seg.pt source="/content/bus.jpg"

"""# 3. **Classification**"""

!yolo task=classify mode=predict model=yolov8n-cls.pt source="/content/bus.jpg"